### ISSUE TITLE
Nexus 5 (Android 版本4.4)在APP無法加載Air Card的圖片

### ISSUE THREAD

**Issue by yiming330** [yiming330/pqi-air-card#1]
請確認一下無法加載的意思是否為 "無法看到圖" 還是 "無法下載圖片"?

**Comment by PQI-APP** [comment]
會有小圖（Pre-View)無法顯示的狀況

**Comment by yiming330** [comment]
是否能再麻煩確認幾點:
1. 消費者所使用的相機型號? 
2. 是所有小圖都看不到, 還是部分? 
3. 是否可以提供screenshot? 
4. 是否可以提供看不到小圖的照片檔案跟資料夾結構

**Comment by yiming330** [comment]
此問題缺乏足夠資訊無法複製, 但是有鑒於Android4.4的compatible issue. 會一併在更新版本後release新的app.
