### ISSUE TITLE
Air Card上傳下載鍵 無法使用

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-card#2]
客戶反應 HTC butterfly S上傳下載按鈕不見; 長按 task switcher 亦無法顯示
機型：HTC butterfly S
版本： Android 4.4.2

此現象與Air Bank 相同...網址如下
Air Bank APP 上傳按鈕不見了
https://github.com/yiming330/pqi-air-bank/issues/3

**Comment by wuboy0307** [comment]
此現象在4.4.2為正常情況，只要是有實體鍵盤的機種，都有可能將menu設定為使用實體鍵盤叫出，差別在於設定在哪一個按鍵上，以及是按一下或是長按，因此若之後有其他hTC機種有此問題應可一併作答。

請參考hTC官方教學
http://www.htc.com/tw/support/htc-butterfly-s/howto/367961.html

您也可以將最近使用的應用程式按鈕設為開啟選單。
進入設定，然後點選顯示、手勢和按鈕 (或顯示與按鈕)。
點選最近使用的應用程式按鈕，選取選單的開啟方式，例如按下或按住按鈕。

**Comment by PQI-APP** [comment]
客戶端回復如下; 依照官網的設定方式,應該是舊版本的方式; 故建議是否有辦法使用實機測試？

HTC他7月份有升級一版本後，就沒有"點選最近使用的應用程式按鈕" 這一個選項，
之前的版本是有的，因為我之前是這樣設定沒錯，直到最近才發現那功能不見了，就不知從何下載照片，
而HTC官網現在所顯示的是早期的版本，我是上網尋別人也有相同問題

**Comment by wuboy0307** [comment]
如果是升級以後設定不見了，那應該就是hTC已經遵照 Google建議的做法，使用虛擬鍵盤 (下圖紅色處)
![2014-09-29 10 25 50](https://cloud.githubusercontent.com/assets/2128976/4440282/301390cc-47c3-11e4-84bf-1358baec83ab.png)

**Comment by yiming330** [comment]
此說明再麻煩回復給客戶端, 請客戶嘗試. 就目前的調查看來, 此為操作上的認知, 並非bug. 請確認.
