### ISSUE TITLE
Air Card   使用PC 時有壞圖

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-card#3]
Some user opens photo image in PC through Air Card, but there are many broken image photos as follows.
When user take out micro SD card from the Air Card and plug into PC directly through card slot, all photo images are normal.
Therefore, photo data is OK but this Air Card doesn’t seem to support data reading perfectly.
Is it Air Card H/W issue or S/W issue or can this user fix this problem by himself?
![image001](https://cloud.githubusercontent.com/assets/8001211/5735892/29ed157a-9c09-11e4-96ac-02edb4dfaabc.png)
![image002](https://cloud.githubusercontent.com/assets/8001211/5735895/32956fc4-9c09-11e4-960c-1a4d2d823ffc.png)
![image003](https://cloud.githubusercontent.com/assets/8001211/5735902/38a42b30-9c09-11e4-9380-c89bd630faba.png)
![image004](https://cloud.githubusercontent.com/assets/8001211/5735904/3d961982-9c09-11e4-8779-ce50b0a9b1d7.png)

**Comment by yiming330** [comment]
這個user回報的現象, 是將air card插入讀卡機, 然後用third party的軟體來讀取照片. 我的猜測, 這是因為Air Card本身電耗太高, 造成讀卡機不正常, 建議使用者用外接式讀卡機, 或是將Air Card自動開啟WiFi的功能關掉.

如果用外接式讀卡機還是有問題, 或是將WiFi關掉還是不行, 那研判有可能是air card的hardware issue.

如果要遠端連線, 我剛剛有用網頁連進Air Card (192.168.1.1), 照片看到都是正常的
![untitled](https://cloud.githubusercontent.com/assets/5311668/5759602/e6ec04c8-9d09-11e4-956c-59cc317d12e8.png)
