### ISSUE TITLE
Air Card APP 在Android 5.0以上版本進入到APP設定畫面會閃退

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-card#4]
User 反應升級到Android 5.0使用Air Card+ APP進到設定畫面會自動閃退, 請幫忙修改更新, 謝謝

PQI FAE
Robin 
分 機: 29847

**Comment by yiming330** [comment]
Started to working on the fix

**Comment by yiming330** [comment]
Fixed, and deployed to Google Play. Version: 1.1.18
